import { StyleSheet } from 'react-native';
import type { AppColors } from '../../theme';
import { accentAlpha, spacing } from '../../theme';

export function createAddRepairStyles(colors: AppColors) {
  const COLORS = {
    bg: colors.bg,
    card: colors.surface,
    border: colors.border,
    input: colors.surface2,
    primary: colors.accent,
    secondary: colors.accent,
    text: colors.text === '#0f172a' ? '#000000' : colors.text,
    subText: colors.textMuted,
  };

  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: COLORS.bg,
    },
    scroll: {
      flex: 1,
    },
    content: {
      paddingBottom: 140,
    },
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingTop: 12,
      paddingBottom: 8,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: COLORS.card,
      borderWidth: 1,
      borderColor: COLORS.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTextWrap: {
      marginLeft: 14,
    },
    headerTitle: {
      color: COLORS.text,
      fontSize: 22,
      fontWeight: '800',
    },
    sectionTitle: {
      color: COLORS.subText,
      fontSize: 12,
      fontWeight: '800',
      marginTop: 12,
      marginBottom: 6,
      marginHorizontal: 18,
      letterSpacing: 0.8,
    },
    orderBanner: {
      marginHorizontal: 18,
      marginBottom: 8,
      backgroundColor: COLORS.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 14,
    },
    orderBannerLabel: {
      color: COLORS.subText,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    orderBannerValue: {
      color: COLORS.primary,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.3,
    },
    accessoryCard: {
      marginHorizontal: 18,
      marginBottom: 8,
      backgroundColor: COLORS.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    accessoryLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    accessoryIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: COLORS.input,
      justifyContent: 'center',
      alignItems: 'center',
    },
    accessoryTitle: {
      color: COLORS.text,
      fontSize: 15,
      fontWeight: '600',
      marginLeft: 10,
    },
    accessoryToggle: {
      flexDirection: 'row',
      backgroundColor: COLORS.input,
      borderRadius: 12,
      padding: 3,
    },
    toggleBtn: {
      paddingVertical: 8,
      paddingHorizontal: 18,
      borderRadius: 10,
    },
    toggleBtnActive: {
      backgroundColor: COLORS.primary,
      borderRadius: 10,
    },
    toggleText: {
      color: COLORS.subText,
      fontSize: 14,
      fontWeight: '700',
    },
    toggleTextActive: {
      color: '#fff',
    },
    problemCard: {
      marginHorizontal: 18,
      marginBottom: 8,
      backgroundColor: COLORS.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 10,
    },
    problemSuggestions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 10,
    },
    statusCard: {
      marginHorizontal: 18,
      marginBottom: 12,
      backgroundColor: COLORS.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 10,
    },
    statusRow: {
      flexDirection: 'row',
      gap: 8,
    },
    lockCard: {
      marginHorizontal: 18,
      marginBottom: 8,
      backgroundColor: COLORS.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 10,
    },
    lockHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    lockInputContainer: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
    },
    paymentCard: {
      marginHorizontal: 18,
      marginBottom: 8,
      backgroundColor: COLORS.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 10,
    },
    paidRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 6,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
    },
    paidLabel: {
      color: COLORS.text,
      fontSize: 14,
      fontWeight: '600',
    },
    photosCard: {
      marginHorizontal: 18,
      marginBottom: 8,
    },
    whatsappCard: {
      marginHorizontal: 18,
      marginBottom: 8,
      backgroundColor: COLORS.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    whatsappLabel: {
      color: COLORS.text,
      fontSize: 13,
      fontWeight: '600',
      flex: 1,
    },
    bottomBtn: {
      position: 'absolute',
      bottom: 16,
      left: 18,
      right: 18,
    },
    paperInput: {
      marginHorizontal: 18,
      marginBottom: 2,
      backgroundColor: COLORS.card,
    },
    imeiPaperInput: {
      flex: 1,
      backgroundColor: COLORS.card,
    },
    scanPaperBtn: {
      borderRadius: 12,
      justifyContent: 'center',
    },
    scanPaperBtnContent: {
      height: 42,
      paddingHorizontal: 8,
    },
    lockPaperInput: {
      marginTop: 3,
      backgroundColor: COLORS.card,
    },
    problemPaperInput: {
      backgroundColor: COLORS.card,
    },
    paymentPaperInput: {
      backgroundColor: COLORS.card,
    },
    savePaperBtn: {
      borderRadius: 12,
      overflow: 'hidden',
    },
    savePaperBtnContent: {
      height: 50,
    },
    savePaperBtnLabel: {
      fontSize: 16,
      fontWeight: '700',
    },
    suggestionsContainer: {
      marginHorizontal: 18,
      backgroundColor: COLORS.card,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 14,
      marginTop: -6,
      marginBottom: 8,
      overflow: 'hidden',
    },
    suggestionItem: {
      padding: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: COLORS.border,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    suggestionName: {
      color: COLORS.text,
      fontWeight: '600',
      fontSize: 14,
    },
    suggestionPhone: {
      color: COLORS.subText,
      fontSize: 12,
    },
    brandSuggestContainer: {
      marginHorizontal: 18,
      backgroundColor: COLORS.card,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 14,
      marginTop: -6,
      marginBottom: 12,
      overflow: 'hidden',
      maxHeight: 200,
    },
    modalWrap: {
      flex: 1,
      backgroundColor: colors.text === '#FFFFFF' ? 'rgba(5,8,22,0.85)' : 'rgba(15,23,42,0.45)',
      justifyContent: 'center',
      padding: spacing.lg,
    },
    modalOuter: {
      zIndex: 1,
      width: '100%',
    },
    modalSheet: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: 'rgba(124,58,237,0.2)',
      overflow: 'hidden',
      shadowColor: '#7C3AED',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
      elevation: 12,
    },
    modalTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.lg,
      letterSpacing: -0.3,
    },
    modalSub: {
      color: colors.textMuted,
      fontSize: 14,
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.sm,
    },
    modalCloseBtn: {
      position: 'absolute',
      top: spacing.md,
      right: spacing.md,
      zIndex: 10,
      padding: 4,
    },
    paymentModalBody: {
      padding: spacing.lg,
      gap: spacing.md,
    },
    paymentButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
      gap: 8,
    },
    paymentButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
  });
}

export type AddRepairStyles = ReturnType<typeof createAddRepairStyles>;
